TangrotiSchool/Pages/Admin/AdminHome.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TangrotiSchool.Pages.Admin
{
    public class AdminHomeModel : PageModel
    {
        [Authorize]
        public void OnGet()
        {
            try
            {

            }
            catch(Exception ex)
            {
                Console.Write(ex);
            }
        }

        public async Task<IActionResult> OnPostLogOff()
        {
            try
            {
                var authenticationManager = Request.HttpContext;

                await authenticationManager.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            catch (Exception ex)
            {

                throw ex;
            }

            return this.RedirectToPage("/Index");
        }
    }
}

TangrotiSchool/Pages/Admin/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TangrotiSchool.Models.DB;
using System.Linq;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace TangrotiSchool.Pages.Admin
{
    public class IndexModel : PageModel
    {
        private readonly SchoolTangrotiContext databaseManager;

        /// <summary>
        /// Default constructor intialization
        /// </summary>
        /// <param name="databaseMangerContext">DataBase Manager context</param>
        public IndexModel(SchoolTangrotiContext databaseMangerContext)
        {
            try
            {

                this.databaseManager = databaseMangerContext;
            }
            catch(Exception ex)
            {
                Console.Write(ex);
            }
        }

        [BindProperty]
        public LoginViewModel LoginModel { get; set; }

        public IActionResult OnGet()
        {
            try
            {
                if(this.User.Identity.IsAuthenticated)
                {
                    return this.RedirectToPage("/Admin/AdminHome");
                }

            }
            catch(Exception ex)
            {
                Console.Write(ex);
            }

            return this.Page();
        }

        #region On Post Login Method

        public async Task<IActionResult> OnPostLogin()
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var loginInfo =await this.databaseManager.LoginByUsernamePasswords(this.LoginModel.Username, this.LoginModel.Password);

                    if(loginInfo !=null && loginInfo.Count ()>0)
                    {
                        var logindetails = loginInfo.First();

                        await this.SignInUser(logindetails.Username, false);
                        return this.RedirectToPage("/Admin/AdminHome");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Invalid UserName or Password");
                    }
                }
            }
            catch(Exception ex)
            {
                Console.Write(ex);
            }

            return this.Page();
        }

        private async Task SignInUser(string userName , bool isPresistent)
        {
            var claims = new List<Claim>();
           try
            {
                claims.Add(new Claim(ClaimTypes.Name, userName));
                var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimPrinciple = new ClaimsPrincipal(claimIdentity);
                var authenticationManager = Request.HttpContext;

                await authenticationManager.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrinciple, new AuthenticationProperties() { IsPersistent = isPresistent });


            }
            catch(Exception ex)
            {

            }
        }

        #endregion
    }
}

TangrotiSchool/Pages/Admin/AdminHome.cshtml
@page
@model TangrotiSchool.Pages.Admin.AdminHomeModel
@{
   ViewBag.title = "Admin Login";
}

<h2>@ViewBag.title</h2>
<div class="jumbotron">
    <h1>Welcome</h1>
    <p class="lead" >Login From "@User.Identity.Name" Account</p>
</div>

<div class="row">
    <div class="col-md-8">
        <form method="post" role="form" class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button asp-page-handler="LogOff" class="btn btn-default" >Log Off</button>
            </div>
        </div>
</form>
    </div>
</div>

TangrotiSchool/Pages/Admin/Index.cshtml
@page
@model TangrotiSchool.Pages.Admin.IndexModel
@{
    ViewBag.Title = "Login TO Portal";
}
<h2>@ViewBag.title</h2>
<div class="row">
    <div class="col-md-8">
        <section>
            <form method="post" role="form" class="form-horizontal">
                @Html.AntiForgeryToken()
                <h4>Use a Local Account to log in</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(m => m.LoginModel.Username, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.LoginModel.Username, "", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.LoginModel.Username, "", new { @class = "text- danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.LoginModel.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.LoginModel.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.LoginModel.Password, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button asp-page-handler="Login" class="btn btn-default">Log in</button>
                    </div>
                </div>

            </form>
        </section>
    </div>
</div>